version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=discord-dashboard
    command: ["mongod", "--bind_ip_all", "--auth"]
    volumes:
      - mongo_data:/data/db

  backend:
    build: ../../backend
    working_dir: /app
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/discord-dashboard
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  bot:
    build: ../../backend
    command: npm run bot
    working_dir: /app
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/discord-dashboard
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - backend

  frontend:
    build: ../../frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:5000}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongo_data:
